name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/DFO.sln
    - name: Build
      run: dotnet build --no-restore src/DFO.sln
    - name: Publish
      run: dotnet publish -c Release -o publish src/DFO.sln
    - name: Pack
      uses: papeloto/action-zip@v1
      with:
        files: publish/ 
        dest: dfo.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dfo.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
